/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppDataQualityRouteImport } from './routes/_app.data-quality'
import { Route as AppAskRouteImport } from './routes/_app.ask'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as AppProjectsProjectIdReportRouteImport } from './routes/_app.projects.$projectId.report'
import { Route as AppProjectsProjectIdDataQualityRouteImport } from './routes/_app.projects.$projectId.data-quality'
import { Route as AppProjectsProjectIdAskRouteImport } from './routes/_app.projects.$projectId.ask'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppDataQualityRoute = AppDataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdReportRoute =
  AppProjectsProjectIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDataQualityRoute =
  AppProjectsProjectIdDataQualityRouteImport.update({
    id: '/data-quality',
    path: '/data-quality',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdAskRoute = AppProjectsProjectIdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AppAskRoute
  '/data-quality': typeof AppDataQualityRoute
  '/portfolio': typeof AppPortfolioRoute
  '/report': typeof AppReportRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/$projectId/ask': typeof AppProjectsProjectIdAskRoute
  '/projects/$projectId/data-quality': typeof AppProjectsProjectIdDataQualityRoute
  '/projects/$projectId/report': typeof AppProjectsProjectIdReportRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AppAskRoute
  '/data-quality': typeof AppDataQualityRoute
  '/portfolio': typeof AppPortfolioRoute
  '/report': typeof AppReportRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/projects/$projectId/ask': typeof AppProjectsProjectIdAskRoute
  '/projects/$projectId/data-quality': typeof AppProjectsProjectIdDataQualityRoute
  '/projects/$projectId/report': typeof AppProjectsProjectIdReportRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ask': typeof AppAskRoute
  '/_app/data-quality': typeof AppDataQualityRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/report': typeof AppReportRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/$projectId/ask': typeof AppProjectsProjectIdAskRoute
  '/_app/projects/$projectId/data-quality': typeof AppProjectsProjectIdDataQualityRoute
  '/_app/projects/$projectId/report': typeof AppProjectsProjectIdReportRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/data-quality'
    | '/portfolio'
    | '/report'
    | '/settings'
    | '/upload'
    | '/projects/$projectId'
    | '/projects/$projectId/ask'
    | '/projects/$projectId/data-quality'
    | '/projects/$projectId/report'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/data-quality'
    | '/portfolio'
    | '/report'
    | '/settings'
    | '/upload'
    | '/projects/$projectId/ask'
    | '/projects/$projectId/data-quality'
    | '/projects/$projectId/report'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ask'
    | '/_app/data-quality'
    | '/_app/portfolio'
    | '/_app/report'
    | '/_app/settings'
    | '/_app/upload'
    | '/_app/projects/$projectId'
    | '/_app/projects/$projectId/ask'
    | '/_app/projects/$projectId/data-quality'
    | '/_app/projects/$projectId/report'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-quality': {
      id: '/_app/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof AppDataQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/report': {
      id: '/_app/projects/$projectId/report'
      path: '/report'
      fullPath: '/projects/$projectId/report'
      preLoaderRoute: typeof AppProjectsProjectIdReportRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/data-quality': {
      id: '/_app/projects/$projectId/data-quality'
      path: '/data-quality'
      fullPath: '/projects/$projectId/data-quality'
      preLoaderRoute: typeof AppProjectsProjectIdDataQualityRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/ask': {
      id: '/_app/projects/$projectId/ask'
      path: '/ask'
      fullPath: '/projects/$projectId/ask'
      preLoaderRoute: typeof AppProjectsProjectIdAskRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdAskRoute: typeof AppProjectsProjectIdAskRoute
  AppProjectsProjectIdDataQualityRoute: typeof AppProjectsProjectIdDataQualityRoute
  AppProjectsProjectIdReportRoute: typeof AppProjectsProjectIdReportRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdAskRoute: AppProjectsProjectIdAskRoute,
  AppProjectsProjectIdDataQualityRoute: AppProjectsProjectIdDataQualityRoute,
  AppProjectsProjectIdReportRoute: AppProjectsProjectIdReportRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppAskRoute: typeof AppAskRoute
  AppDataQualityRoute: typeof AppDataQualityRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppReportRoute: typeof AppReportRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAskRoute: AppAskRoute,
  AppDataQualityRoute: AppDataQualityRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppReportRoute: AppReportRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
